# Welcome to Fvwm's Jekyll Config!
#
#   These settings set site defaults and site
#   site variables, {{ site.variablename }}

# Site settings
title: The Offical FVWM Home Page
email: fvwm-owner@fvwm.org
description: > # this means to ignore newlines until "baseurl:"
  FVWM is an extremely powerful ICCCM-compliant multiple virtual desktop
  window manager for the X Window system.
baseurl: "" # The subpath site is hosted
wikiurl: "/Wiki" # The wiki subpath (must include $basepath)
url: "https://www.fvwm.org" # the base hostname & protocol for your site

# FVWM release version
fvwm2-version: 2.7.0
fvwm3-version: 1.1.4

# Highlight fvwm2rc code
fvwm2rc: False

# Navigation Menu
nav:
  - name: Wiki
    url: "/Wiki/"
  - name: Community
    url: "/Community/"
  - name: Forums/Discussions
    url: "https://github.com/fvwmorg/fvwm3/discussions"
  - name: GitHub
    url: "https://github.com/fvwmorg/"
  - name: Archive
    url: "/Archive/"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "fvwm3"

